typography_spectrum: 0.2639748342335224
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4486234770156443
  lightness: 0.4820536356419325
  saturation: 0.3119216812774539
  rhythmicContrast: 0.053217560751363635
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7905796358827502
analytics:
  google: null
  facebook: null
  twitter: null
name: Intermodal Connection
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Transportation | South Jersey
purpose: []
